finally_called_uncaught_exception(volatile unsigned int* called)
{
    TRY {
    }
    FINALLY {
        (*called)++;
    }
    ENDTRY;
}
